### ISSUE TITLE
Fix the cron/git job

### ISSUE THREAD

**Issue by llrs** [llrs/cranis#1]
Make it to update hourly. 
I use checkout v2 compared to cransays, but I don't understand why it is still failing. Do I miss to set up some secrets or deploy key?

**Comment by maelle** [comment]
with a deploy_pat secret but it's only for pkgdown

**Comment by maelle** [comment]
however for pkgdown these days there's `usethis::use_github_action("pkgdown")`, maybe it gives something better

**Comment by llrs** [comment]
Hi Maëlle, thanks for the reply.

I have a DEPLOY_PAT secret already set, but the error is about git authentication. Yeah, I saw the new action. but didn't want to change too much from cransays. 
If I don't find a way I will look into that action and use it.

**Comment by llrs** [comment]
Solved! Completely overhauled the workflows/GHA tough.
